# Generated by Django 5.1.4 on 2024-12-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_utilisateur'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateur',
            new_name='User',
        ),
    ]
